version: '3'
services:
  selenium:
    image: selenium/standalone-chrome:3.14
    container_name: selenium
    volumes:
      - ./website/:/opt/rails
    ports:
      - "4444:4444"
    networks:
      - internal
  redis:
    image: "redis:4"
    networks:
      - internal
  mysql:
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_USER=exercism_reboot
      - MYSQL_PASSWORD=exercism_reboot
    image: "mariadb:10.3"
    restart: always
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - ./setup/mysql:/docker-entrypoint-initdb.d
      - exercism-dev-mysql:/var/lib/mysql
    networks:
      - internal
  rails:
    build: .
    volumes:
      - ./website/:/opt/rails
    environment:
      MYSQL_HOST: 'mysql'
      REDIS_URL: 'redis://redis:6379/1'
      TESTS_TEAMS_HOST: 'http://teams.exercism.local'
    depends_on:
      - mysql
      - redis
      - selenium
    ports:
      - "3000:3000/tcp"
      - "3010:3010/tcp"
    networks:
      internal:
        aliases:
          - teams.exercism.local
          - exercism.local
      external:
        aliases:
          - teams.exercism.local
          - exercism.local

networks:
  internal:
  external:

volumes:
  exercism-dev-mysql:
