version: '3'
services:
  redis:
    image: "redis:4"
    networks:
      - internal
  mysql:
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_USER=exercism_reboot
      - MYSQL_PASSWORD=exercism_reboot
    image: "mariadb:10.3"
    restart: always
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - ./setup/mysql:/docker-entrypoint-initdb.d
      - exercism-dev-mysql:/var/lib/mysql
    networks:
      - internal
  rails:
    build: .
    volumes:
      - ./website/:/opt/rails
    environment:
      MYSQL_HOST: 'mysql'
      REDIS_URL: 'redis://redis:6379/1'
    depends_on:
      - mysql
      - redis
    ports:
      - "3000:3000/tcp"
    networks:
      internal:
      external:
        aliases:
          - teams.exercism.local
          - exercism.local

networks:
  internal:
  external:

volumes:
  exercism-dev-mysql:
